"""Assemble results/*.json into synthesis.md -- the reconciled verdict plus an assumption
ledger tied to DAG edges. Run after 01-04 (it reads their JSON outputs)."""
from __future__ import annotations

import os

from co60lib import HERE, banner, load_result


def fmt(x, nd=2):
    try:
        return f"{float(x):.{nd}f}"
    except Exception:
        return str(x)


def main():
    dag = load_result("dag.json")
    qc = load_result("qc.json")
    rep = load_result("reproduce.json")
    causal = load_result("causal.json")
    bias = load_result("bias.json")

    doss = {r["dataset"]: r for r in rep["doss_sir"]}
    breast = causal["internal_breast"]["hr_per_100msv"]
    grad = causal["gradients"]
    std = causal["standardization"]
    me = bias["measurement_error"]
    ev = {r["site"]: r for r in bias["evalues"]}
    fdr = bias["multiple_comparisons"]

    lines = []
    W = lines.append
    W("# Did Co-60 exposure cause cancer in the Taiwan rebar cohort? — reconciled verdict\n")
    W("*Generated by `05_synthesis.py` from `results/*.json`. All numbers below are computed "
      "by the pipeline from the digitized open-access tables; see `README.md` for provenance.*\n")

    W("## 0. Transcription integrity")
    W(f"- {qc['n_pass']}/{qc['n_total']} QC checks passed (digitized cells reconcile to the "
      "cohort totals reported by Hsieh/Chang 2017).\n")

    W("## 1. The two headline results are both real and not in conflict")
    W(f"- **External SIR (Doss 2018, reproduced exactly):** "
      f"{fmt(doss['hsieh2017_2012']['sir'])} "
      f"(95% CI {fmt(doss['hsieh2017_2012']['ci_low'])}–{fmt(doss['hsieh2017_2012']['ci_high'])}) "
      f"through 2012 — an apparent *deficit* of cancer vs the general Taiwan population.")
    W(f"- **Internal dose–response (this reanalysis):** positive and significant. Age-adjusted "
      f"breast-cancer HR per 100 mSv = {fmt(breast['estimate'],3)} "
      f"(95% CI {fmt(breast['ci_low'],3)}–{fmt(breast['ci_high'],3)}, p={fmt(breast['pvalue'],3)}); "
      f"marginal solid-cancer and leukaemia rate gradients are monotonic in dose.")
    W("- A Pearl reading: the external SIR conditions on a **non-exchangeable reference "
      "population** (the `Selection` node). The internal gradient conditions on age instead. "
      "They answer different causal questions, so 'protective SIR' and 'harmful dose–response' "
      "coexist without contradiction.\n")

    W("## 2. Why the SIR looks 'protective' — an age-structure artifact")
    W(f"- Age-at-exposure rate gradient = **{fmt(grad['age_gradient'],1)}×** "
      f"(oldest/youngest) vs a dose gradient of only **{fmt(grad['dose_gradient'],1)}×**.")
    W(f"- Applying the cohort's own age-specific rates under an older, population-like "
      f"weighting raises the standardized rate **{fmt(std['ratio'],1)}×** — the deficit is "
      f"manufactured by the cohort being young (mean age at first exposure ~17), not by "
      f"radiation being protective.")
    W("- The Chen/Luan hormesis claim (observed cancer *deaths* ≈ 7 vs ~232 'expected') is the "
      "same artifact in a stronger form: a young cohort, a mortality (not incidence) endpoint, "
      "short follow-up, and an all-ages external comparator.\n")

    W("## 3. Is the internal signal robust? (bias analyses)")
    W(f"- **Unmeasured confounding (E-values):** breast E-value = "
      f"{fmt(ev['female_breast']['evalue_point'])} (point), "
      f"{fmt(ev['female_breast']['evalue_ci'])} (CI limit); leukaemia (excl MM&CLL) = "
      f"{fmt(ev['leukaemia_excl_mm_cll']['evalue_point'])} / "
      f"{fmt(ev['leukaemia_excl_mm_cll']['evalue_ci'])}. These are **modest** — a confounder "
      "(e.g. reproductive history for breast) associated ~1.2–1.6× with both dose and cancer "
      "could weaken the signal. This is the single biggest caveat, because those confounders "
      "are unmeasured and the DAG shows their backdoor paths remain **open**.")
    W(f"- **Dose measurement error:** simulation recovers ERR/Sv = {fmt(me['oracle'])} from true "
      f"dose, {fmt(me['classical'])} under classical error (**attenuated** toward null), and "
      f"{fmt(me['berkson'])} under Berkson error (**unbiased**). Reconstruction error therefore "
      "more likely **understates** the true slope than inflates it.")
    W(f"- **Exposure-model sensitivity:** the dose–response *sign and significance* are "
      "invariant to the assumed within-group dose; only the *magnitude* moves. Magnitude "
      "claims from aggregate cells should be treated as order-of-magnitude only.")
    survivors = [s['site'] for s in fdr['survivors'] if s['survives_fdr']]
    W(f"- **Multiple comparisons:** under Benjamini–Hochberg FDR<0.05 the surviving site "
      f"signals are {survivors}. By contrast Hwang 2006 screened ~77 cells "
      f"(~{fmt(fdr['hwang_expected_false_positives'],1)} false positives expected by chance), "
      f"its 'elevated' sites resting on ≤7 cases — those single-count SIR hits should be "
      f"discounted; the dose–response signals should not.\n")

    W("## 4. Verdict")
    W("- **The data are most consistent with a genuine, positive causal dose–response** for "
      "leukaemia and (age-modified) breast cancer, strongest in those exposed young.")
    W("- **The apparent protective effect is an artifact** of age structure and a "
      "non-exchangeable external reference — it is not evidence for hormesis.")
    W("- **But identification is not clean:** the estimand is not point-identified from the "
      "available data; it rests on the authors' quasi-randomization assumption (unaware "
      "residents ⇒ dose ⟂ lifestyle | age). The modest E-values mean a moderate unmeasured "
      "confounder could materially change the magnitude, especially for breast cancer. A "
      "definitive answer needs the restricted individual-level microdata.\n")

    W("## 5. Assumption ledger (each tied to a DAG edge)")
    W("| Assumption | DAG edge it addresses | Status in this analysis |")
    W("|---|---|---|")
    W("| Dose ⟂ lifestyle given age (quasi-randomization) | `Smoking→Cancer`, `SES→Cancer` backdoors | **Assumed, not verified**; probed by E-values |")
    W("| Reproductive history ⟂ dose | `ReproHistory→Cancer` (breast) | **Open backdoor**; unmeasured — largest breast-cancer caveat |")
    W("| Representative within-group dose values | `AssignedDose` scale | **Assumed**; sign/significance shown invariant, magnitude not |")
    W("| Classical vs Berkson error mix | `TrueDose→AssignedDose` (`DoseError`) | Simulated; classical attenuates, so slope is conservative |")
    W("| External reference exchangeability | `Selection` (SIR design) | **Rejected**; internal gradient used instead |")
    W("| Independence of individuals | `Building` cluster | Aggregate models sidestep; building-level SES backdoor remains open |")
    W("")
    W(f"**Open backdoor paths under the available adjustment set** "
      f"(`{', '.join(dag['available_adjustment']['adjustment_set'])}`):")
    for p in dag["available_adjustment"]["open_backdoor_paths"]:
        W(f"- `{p}`")
    W("")

    out = os.path.join(HERE, "synthesis.md")
    with open(out, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    banner("Synthesis written")
    print(f"  {out}")


if __name__ == "__main__":
    main()
